services:
  mongodb:
    image: 'mongo:latest'
    container_name: chirper-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=chirper_database'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27010:27017'
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    container_name: chirper-postgres
    environment:
      - 'POSTGRES_DB=chirper_database'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5430:5432'
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    container_name: chirper-redis
    ports:
      - '6370:6379'
    restart: unless-stopped
